### ISSUE TITLE
Error when Train A2C Agent on MSMD  

### ISSUE THREAD

**Issue by lakebodhi** [CPJKU/score_following_game#1]
Hi!

I am training the model by using the provided code 
`python sf_experiment.py --net ScoreFollowingNetMSMDLCHSDeepDo --train_set <PATH-TO-DATA-ROOT>/score_following_game_data/msmd_all/msmd_all_train --eval_set <PATH-TO-DATA-ROOT>/score_following_game_data/msmd_all/msmd_all_valid --game_config game_configs/mutopia_lchs1.yaml --log_root <LOG-ROOT>/runs_ISMIR18 --param_root <LOG-ROOT>/params_ISMIR18
`
However, I got an EOFError during the multiprocessing stage. 

What should I do about this issue please? 

The detailed traceback is:

`Traceback (most recent call last):
  File "sf_experiment.py", line 237, in <module>
    dump_dir=dump_dir)
  File "/Users/Lakebodhi/score_following_game/score_following_game/reinforcement_learning/reinforcement_learning/algorithms/a2c/a2c.py", line 37, in train
    first_observations = self.env.reset()
  File "/Users/Lakebodhi/score_following_game/score_following_game/environment/multi_modal_subproc_vec_env.py", line 39, in reset
    remotes_list = [remote.recv() for remote in self.remotes]
  File "/Users/Lakebodhi/score_following_game/score_following_game/environment/multi_modal_subproc_vec_env.py", line 39, in <listcomp>
    remotes_list = [remote.recv() for remote in self.remotes]
  File "/anaconda3/envs/score_following/lib/python3.6/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/anaconda3/envs/score_following/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/anaconda3/envs/score_following/lib/python3.6/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
`

**Comment by fhenkel** [comment]
Hi,

I just reinstalled the project following the instructions in the Readme (installing with conda) and could not reproduce your error.
Could you provide some more details on what you did exactly? Did you install the project requirements with conda?

**Comment by lakebodhi** [comment]
> Hi,
> 
> I just reinstalled the project following the instructions in the Readme (installing with conda) and could not reproduce your error.
> Could you provide some more details on what you did exactly? Did you install the project requirements with conda?

Hi!

I installed with conda as well by running the code (my operating system is macOS Mojave 10.14.2): 

`conda env create -f environment.yml`

and then

`python3 setup.py develop --user`

Seems like the error only comes with a2c agent, I tried to use the 'reinforce' agent, and it works fine.


>

**Comment by stefan-balke** [comment]
I once had the inferencing running on Mac OSX but never the training.
From my experience (and believe me, I spent hours...) on setting these things up on Mac OS, I usually got very frustrated in the end...
If you have the possibility to run it on an Ubuntu it will save you a lot of time setting up this.

**Comment by lakebodhi** [comment]
> I once had the inferencing running on Mac OSX but never the training.
> From my experience (and believe me, I spent hours...) on setting these things up on Mac OS, I usually got very frustrated in the end...
> If you have the possibility to run it on an Ubuntu it will save you a lot of time setting up this.

Ok, I will run it on Ubuntu. Thanks!

**Comment by lakebodhi** [comment]
> Hi,
> 
> I just reinstalled the project following the instructions in the Readme (installing with conda) and could not reproduce your error.
> Could you provide some more details on what you did exactly? Did you install the project requirements with conda?

May I ask which version of python did you use?

**Comment by fhenkel** [comment]
Python 3.6.8
