### ISSUE TITLE
Score bar follower

### ISSUE THREAD

**Issue by weefeen** [CPJKU/score_following_game#11]
Hello

thank you for all your work.

I need to sync pre-recorded music (acoustic piano recorded with mic music) with measures of a corresponding music score.

The input would be an mp3 or video file (for sound Input) and output would be a simple list with 2 columns like this:

(measure  numbers; sync time of the audio where measure starts)
For example:
[(1, 2s),
(2,3.2s),
(3,4.2s)
….
(144, 165s)
..]

So i am guessing it should a bit easier than your code as music score is not considered but measure numbers only.

do you think your code is a good starting point for me to start and modify to achieve my goal?

Any advice on how to start would be very appreciated 

thank you

**Comment by fhenkel** [comment]
Hi,

Thanks for your interest. I would need a bit more information on your problem to decide whether the code will be a good starting point. If you want, you can drop me a mail to discuss it in more detail.

**Comment by weefeen** [comment]
Hello

Thank you for the proposition. I just left you an Email to your JKU mail address

Best regards
