### ISSUE TITLE
When the trainning stop

### ISSUE THREAD

**Issue by jingjunzhu** [CPJKU/score_following_game#14]
Hi Author, I'm sorry to bother you. When I try to train on the virtual machine, I find that although the program keeps running, it no longer pops up with updates message and there is no new information on the tensorboard since half a day ago, is it normal?
the latest message on tensorboard shows Time is Sat Jan 1, 21:16:44 and Step is 873

**Comment by jingjunzhu** [comment]
my code: python experiment.py --net ScoreFollowingNetNottinghamLS --train_set data/nottingham/nottingham_train --eval_set data/nottingham/nottingham_valid --game_config game_configs/nottingham_ls1.yaml --log_root logg --param_root paramm --agent ppo.

**Comment by fhenkel** [comment]
Hi, is it still consuming GPU resources if you check `nvidia-smi`?

**Comment by jingjunzhu** [comment]
I'm sorry to reply you so late! I had an exam week. I ran the code again yesterday and the progress still killed at 873 step. because I'm using a virtual machine, system is ubuntu20.04, there's no nvidia driver. Should I not be using virtual machines for training?

**Comment by jingjunzhu** [comment]
it seems like the Graphics is Vmware SVGA 3D

**Comment by fhenkel** [comment]
I strongly suggest to use a Nvidia graphics card, if you have one available as this will make the training faster.
Regarding your initial problem, I am currently in the process of cleaning up the code. It might be the case that something was not properly shutdown.

**Comment by jingjunzhu** [comment]
OK. I'll try to change the graphics card and train again. Thank you!
