### ISSUE TITLE
About real performance

### ISSUE THREAD

**Issue by jingjunzhu** [CPJKU/score_following_game#15]
Hello, author, I found that the experiment use 16 real performance pieces to evaluate each method, I wonder if you can provide me those pieces?

**Comment by fhenkel** [comment]
Sure, you can find the data [here](http://www.cp.jku.at/resources/2019_RLScoFo_TISMIR/msmd_real_performances.html).
Let me know if you have any problems.

**Comment by jingjunzhu** [comment]
ok，Thank you so much！
