### ISSUE TITLE
try the pre-trained model on my own piano recordings

### ISSUE THREAD

**Issue by AoxiangGeng** [CPJKU/score_following_game#2]
Hi,

I would like to try the pre-trained model on my own piano recordings, how can I generate the required information in the npz file?

**Comment by fhenkel** [comment]
Hi,

You can find the link to download the MSMD data in the corresponding repository:
https://github.com/CPJKU/msmd

Once you have the data, you can create the required npz files with this script:
https://github.com/CPJKU/score_following_game/blob/rc1/score_following_game/data_processing/prepare_mutopia.py
