### ISSUE TITLE
Live audio input

### ISSUE THREAD

**Issue by piegamesde** [CPJKU/score_following_game#3]
Is there a way to input audio of a live performance? Or must everything be pre-recorded?

**Comment by fhenkel** [comment]
Hi,

for this project we only used pre-recorded audio for convenience.
However, it should not be a problem to extend this to some live input using e.g. the [online-processor of madmom](https://madmom.readthedocs.io/en/latest/modules/processors.html#madmom.processors.OnlineProcessor).

Currently it is not on our agenda to implement this, but in case you need help just drop us a message.

**Comment by piegamesde** [comment]
I haven't poked the code of this project yet, but I may give it a try. Where should I look first to get started?

**Comment by fhenkel** [comment]
I would get familiar with the [test script](https://github.com/CPJKU/score_following_game/blob/tismir-2019/score_following_game/test_agent.py). In the script you will find two things that will be important: The data loading part (datapool) and later on the RL environment, which I guess would require the most changes.

**Comment by piegamesde** [comment]
How does that code relate to the `audio_thread.py`? I see that it loads an audio file and plays it back, but is this the actual data used for the model or is this just for display purposes?

**Comment by fhenkel** [comment]
That is just for display purposes. In the `step` function in  `score_following_env.py` line 106 you will see how it is used.

**Comment by piegamesde** [comment]
Sadly, the concept of a song together with music sheet, note onsets and audio is deeply rooted in the framework. This needs to be split up in a "sheet" part and an "audio performance", but we still need both together for learning.
