### ISSUE TITLE
experiment.py

### ISSUE THREAD

**Issue by YiBenjing456** [CPJKU/score_following_game#5]
Hi,
    I ran the experiment.py, there is an error of ModuleNotFoundError: No module named 'baselines.common.vec_env.shmem_vec_env', I have baselines installed, so could you please tell me which version of baselines did you use?
    Besides, it always said cannot find the wav files when I ran "python test_agent.py --data_set ./data/test_sample --piece Anonymous__lesgraces__lesgraces --game_config game_configs/mutopia_lchs1.yaml --agent_type human 
".
    Could you please help?

**Comment by fhenkel** [comment]
Hi,
the last time i checked, I used baselines 0.1.5. I think the current version is on 0.1.6, but that should still be fine as the `shmem_vec_env.py` is in the same package.
Did you install the baselines package within the score_following environment, i.e.
1. Activate the environment
2. go to the folder with the baselines
3. run `pip install -e .` (within the activated environment)

If this does not work, you could also try adding the path to the baseline package to the `PYTHONPATH`.

**Comment by YiBenjing456** [comment]
> Hi,
> the last time i checked, I used baselines 0.1.5. I think the current version is on 0.1.6, but that should still be fine as the `shmem_vec_env.py` is in the same package.
> Did you install the baselines package within the score_following environment, i.e.
> 
> 1. Activate the environment
> 2. go to the folder with the baselines
> 3. run `pip install -e .` (within the activated environment)
> 
> If this does not work, you could also try adding the path to the baseline package to the `PYTHONPATH`.

Yeah thank you, now the baselines has been solved, but another question is that when i running testagent, it seems the wav file can not be found, is this related to the windows os? The code can be only used in Mac and Linux?

**Comment by fhenkel** [comment]
I tried to address some issues on windows [here](https://github.com/CPJKU/score_following_game/issues/4#issuecomment-666372992).

But unfortunately there is (or at least was) some problem regarding fluidsynth on Windows.
The code is definitely runable on Linux, as I did the experiments on an Ubuntu machine.
For Mac there could still be some issues as i didn't try to train an agent using macOS, however running the `test_agent.py` script in human mode should also work fine.

The easiest way would be to run the whole thing on an Ubuntu System (or in a Virtual Machine).
Also, feel free to drop me a mail if you need more help, besides the Windows issue (which I'm currently not able to solve).
You should be able to find my address in the paper.
