### ISSUE TITLE
code test

### ISSUE THREAD

**Issue by AutoNeuroDrive** [CPJKU/score_following_game#6]
I run the code on Linux, but the code only lasts for about 2seconds. The outputs on the command window are shown as follows. So could you please check whether the code run correctly?
/home/dongyang/Anaconda/lib/python3.8/site-packages/pretty_midi/pretty_midi.py:97: RuntimeWarning: Tempo, Key or Time signature change events found on non-zero tracks.  This is not a valid type 0 or type 1 MIDI file.  Tempo, Key or Time Signature may be wrong.
  warnings.warn(
fluidsynth: warning: No preset found on channel 9 [bank=128 prog=0]
fluidsynth: warning: SDL2 not initialized, SDL2 audio driver won't be usable
fluidsynth: warning: SDL2 not initialized, SDL2 audio driver won't be usable
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card

**Comment by fhenkel** [comment]
This looks like an issue with Fluidsynth.
Can you please check if the following command works:

`fluidsynth -F test.wav -O s16 -T wav <soundfont> <midifile>`

Replace `soundfont` with the path to the provided soundfont in the repo and `midifile` with the path to an arbitrary MIDI file.

The output should look something like this:

```
Copyright (C) 2000-2018 Peter Hanappe and others.
Distributed under the LGPL license.
SoundFont(R) is a registered trademark of E-mu Systems, Inc.

fluidsynth: warning: No preset found on channel 9 [bank=128 prog=0]
Rendering audio to file 'test.wav'..

```

**Comment by AutoNeuroDrive** [comment]
> This looks like an issue with Fluidsynth.
> Can you please check if the following command works:
> 
> `fluidsynth -F test.wav -O s16 -T wav <soundfont> <midifile>`
> 
> Replace `soundfont` with the path to the provided soundfont in the repo and `midifile` with the path to an arbitrary MIDI file.
> 
> The output should look something like this:
> 
> ```
> Copyright (C) 2000-2018 Peter Hanappe and others.
> Distributed under the LGPL license.
> SoundFont(R) is a registered trademark of E-mu Systems, Inc.
> 
> fluidsynth: warning: No preset found on channel 9 [bank=128 prog=0]
> Rendering audio to file 'test.wav'..
> ```

It works will with the fluidsynth -F test.wav -O s16 -T wav <soundfont> <midifile>. The problem now is Cannot connect to server socket err = no such file or dictionary
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock


Did you have this issue before?

**Comment by fhenkel** [comment]
> It works will with the fluidsynth -F test.wav -O s16 -T wav . The problem now is Cannot connect to server socket err = no such file or dictionary

Does that mean, that the MIDI is correctly rendered to test.wav and you can listen to it? Or do you get this socket error already when you run the command?

**Comment by AutoNeuroDrive** [comment]
The MIDI can be correctly rendered to test.wav which can be played by my desktop. I fixed the problem of jack can not be connected. Now the issue is "ALSA: invalid type for card". This is my first time to use ALSA, I just think maybe the reason is that my usb devices such as the player and microphone are not compatible with ALSA? Do you think this is a possible issue?


Much thanks to you for your attention!!!


Best Regards!
Dongyang Li
---------------------------------
Dongyang Li
Department of Control Science and Engineering
College of Electronics and Information Engineering
Tongji University
Shanghai, China
Address: 4800 Cao’an Rd.Shanghai, China 201804
Tel: + 86 13167236548
Email: lidongyang0412@163.com


On 2/17/2021 02:50，Florian Henkel<notifications@github.com> wrote：

It works will with the fluidsynth -F test.wav -O s16 -T wav . The problem now is Cannot connect to server socket err = no such file or dictionary

Does that mean, that the MIDI is correctly rendered to test.wav and you can listen to it? Or do you get this socket error already when you run the command?

**Comment by fhenkel** [comment]
I think I remember a similar error (not for this project, but another).
It was related to `portaudio` and was fixed by installing it using this command:
`conda install -c nwani portaudio`

I'm not sure though if it will help here, as we are not even using `portaudio`in this project. But it might still be worth trying.

Other than that, you mentioned external usb devices. Did you check whether the code works if those are unplugged?

**Comment by AutoNeuroDrive** [comment]
It didn't work too. I am going to try to run the code on laptop. Could you please tell me which version of Linux did you use to run it? I just want to ensure the correctness of the OS. Much thanks to you again!


Best Regards!
Dongyang Li
---------------------------------
Dongyang Li
Department of Control Science and Engineering
College of Electronics and Information Engineering
Tongji University
Shanghai, China
Address: 4800 Cao’an Rd.Shanghai, China 201804
Tel: + 86 13167236548
Email: lidongyang0412@163.com


On 2/18/2021 02:36，Florian Henkel<notifications@github.com> wrote：

I think I remember a similar error (not for this project, but another).
It was related to portaudio and was fixed by installing it using this command:
conda install -c nwani portaudio

I'm not sure though if it will help here, as we are not even using portaudioin this project. But it might still be worth trying.

Other than that, you mentioned external usb devices. Did you check whether the code works if those are unplugged?

**Comment by fhenkel** [comment]
The code was tested with Ubuntu 18.04 and Python 3.6.

**Comment by AutoNeuroDrive** [comment]
> The code was tested with Ubuntu 18.04 and Python 3.6.
It seems the code run successfully, but there was no music playing and no score figure. Does it run correctly? The outputs of the terminal is listed as follows. The code was run in Ubuntu 18.04.5 and Python 3.6.



(score_following) dongyang@dongyang-G5-5590:~/ScoreFollowing/score_following_game-tismir-2019$ python test_agent.py --data_set ./data/test_sample --piece Anonymous__lesgraces__lesgraces --game_config game_configs/mutopia_lchs1.yaml --agent_type optimal 
/home/dongyang/anaconda3/envs/score_following/lib/python3.6/site-packages/pretty_midi/pretty_midi.py:100: RuntimeWarning: Tempo, Key or Time signature change events found on non-zero tracks.  This is not a valid type 0 or type 1 MIDI file.  Tempo, Key or Time Signature may be wrong.
  RuntimeWarning)
fluidsynth: warning: No preset found on channel 9 [bank=128 prog=0]
fluidsynth: warning: Failed to pin the sample data to RAM; swapping is possible.
fluidsynth: warning: Failed to pin the sample data to RAM; swapping is possible.
ffmpeg version 3.4.8-0ubuntu0.2 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  configuration: --prefix=/usr --extra-version=0ubuntu0.2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'Anonymous__lesgraces__lesgraces.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    encoder         : Lavf58.17.101
  Duration: 00:00:40.80, start: 0.000000, bitrate: 1722 kb/s
    Stream #0:0(und): Video: mpeg4 (Simple Profile) (mp4v / 0x7634706D), yuv420p, 498x468 [SAR 1:1 DAR 83:78], 1721 kb/s, 20 fps, 20 tbr, 10240 tbn, 20 tbc (default)
    Metadata:
      handler_name    : VideoHandler
Guessed Channel Layout for Input Stream #1.0 : mono
Input #1, wav, from 'tmp.wav':
  Duration: 00:00:42.86, bitrate: 705 kb/s
    Stream #1:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 44100 Hz, mono, s16, 705 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (mpeg4 (native) -> h264 (libx264))
  Stream #1:0 -> #0:1 (pcm_s16le (native) -> aac (native))
Press [q] to stop, [?] for help
[libx264 @ 0x56466760fae0] using SAR=1/1
[libx264 @ 0x56466760fae0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x56466760fae0] profile High, level 2.2
[libx264 @ 0x56466760fae0] 264 - core 152 r2854 e9a5903 - H.264/MPEG-4 AVC codec - Copyleft 2003-2017 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=15 lookahead_threads=2 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=20 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to 'videos/Anonymous__lesgraces__lesgraces_audio.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    encoder         : Lavf57.83.100
    Stream #0:0(und): Video: h264 (libx264) (avc1 / 0x31637661), yuv420p(progressive), 498x468 [SAR 1:1 DAR 83:78], q=-1--1, 20 fps, 10240 tbn, 20 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      encoder         : Lavc57.107.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: -1
    Stream #0:1: Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, mono, fltp, 69 kb/s
    Metadata:
      encoder         : Lavc57.107.100 aac
frame=  342 fps=0.0 q=28.0 size=     768kB time=00:00:14.02 bitrate= 448.6kbits/frame=  653 fps=651 q=28.0 size=    1792kB time=00:00:29.58 bitrate= 496.3kbits/frame=  816 fps=604 q=-1.0 Lsize=    2487kB time=00:00:40.82 bitrate= 499.0kbits/s speed=30.2x    
video:2118kB audio:345kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.940130%
[libx264 @ 0x56466760fae0] frame I:4     Avg QP:16.69  size: 18499
[libx264 @ 0x56466760fae0] frame P:674   Avg QP:24.55  size:  2918
[libx264 @ 0x56466760fae0] frame B:138   Avg QP:29.79  size:   926
[libx264 @ 0x56466760fae0] consecutive B-frames: 71.2% 18.1%  1.8%  8.8%
[libx264 @ 0x56466760fae0] mb I  I16..4: 39.9% 35.5% 24.6%
[libx264 @ 0x56466760fae0] mb P  I16..4:  1.4%  1.8%  0.9%  P16..4: 22.1%  5.4%  3.2%  0.0%  0.0%    skip:65.3%
[libx264 @ 0x56466760fae0] mb B  I16..4:  0.5%  0.6%  0.2%  B16..8: 17.7%  3.7%  0.8%  direct: 0.9%  skip:75.7%  L0:48.4% L1:42.4% BI: 9.3%
[libx264 @ 0x56466760fae0] 8x8 transform intra:43.0% inter:55.5%
[libx264 @ 0x56466760fae0] coded y,uvDC,uvAC intra: 24.5% 27.6% 19.6% inter: 8.4% 5.7% 2.9%
[libx264 @ 0x56466760fae0] i16 v,h,dc,p: 67% 26%  8%  0%
[libx264 @ 0x56466760fae0] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 24% 15% 59%  1%  0%  0%  0%  0%  1%
[libx264 @ 0x56466760fae0] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 38% 36% 18%  1%  1%  1%  1%  2%  2%
[libx264 @ 0x56466760fae0] i8c dc,h,v,p: 51% 15% 33%  1%
[libx264 @ 0x56466760fae0] Weighted P-Frames: Y:0.0% UV:0.0%
[libx264 @ 0x56466760fae0] ref P L0: 75.5%  5.6% 11.8%  7.1%
[libx264 @ 0x56466760fae0] ref B L0: 82.5% 15.2%  2.3%
[libx264 @ 0x56466760fae0] ref B L1: 98.2%  1.8%
[libx264 @ 0x56466760fae0] kb/s:425.16
[aac @ 0x564667612ae0] Qavg: 181.490

**Comment by fhenkel** [comment]
The output looks fine to me. I just checked the code and the `render_mode` (in `test_agent.py` line 27) is set to 'video', which means that it will directly store the output as a video. I forgot to make this a command line argument.
There should be a folder `videos` containing the output video.

So, after all the issue was Python 3.6 vs 3.8?

**Comment by AutoNeuroDrive** [comment]
I still can not run the human-test code. The outputs are obtained by run the optimal-test. I will try to train the network.


I guess it should be the system version, but I am not sure.....


Thanks very much for your attentions!!!


Best Regards!
Dongyang Li
---------------------------------
Dongyang Li
Department of Control Science and Engineering
College of Electronics and Information Engineering
Tongji University
Shanghai, China
Address: 4800 Cao’an Rd.Shanghai, China 201804
Tel: + 86 13167236548
Email: lidongyang0412@163.com


On 2/20/2021 15:26，Florian Henkel<notifications@github.com> wrote：

The output looks fine to me. I just checked the code and the render_mode (in test_agent.py line 27) is set to 'video', which means that it will directly store the output as a video. I forgot to make this a command line argument.
There should be a folder videos containing the output video.

So, after all the issue was Python 3.6 vs 3.8?

**Comment by AutoNeuroDrive** [comment]
The python version I used now is 3.6.  Furthermore, did you set some additional settings for jack?


Best Regards!
Dongyang Li
---------------------------------
Dongyang Li
Department of Control Science and Engineering
College of Electronics and Information Engineering
Tongji University
Shanghai, China
Address: 4800 Cao’an Rd.Shanghai, China 201804
Tel: + 86 13167236548
Email: lidongyang0412@163.com


On 2/20/2021 16:50，Dongyang Li<lidongyang0412@163.com> wrote：
I still can not run the human-test code. The outputs are obtained by run the optimal-test. I will try to train the network.


I guess it should be the system version, but I am not sure.....


Thanks very much for your attentions!!!


Best Regards!
Dongyang Li
---------------------------------
Dongyang Li
Department of Control Science and Engineering
College of Electronics and Information Engineering
Tongji University
Shanghai, China
Address: 4800 Cao’an Rd.Shanghai, China 201804
Tel: + 86 13167236548
Email: lidongyang0412@163.com


On 2/20/2021 15:26，Florian Henkel<notifications@github.com> wrote：

The output looks fine to me. I just checked the code and the render_mode (in test_agent.py line 27) is set to 'video', which means that it will directly store the output as a video. I forgot to make this a command line argument.
There should be a folder videos containing the output video.

So, after all the issue was Python 3.6 vs 3.8?

**Comment by AutoNeuroDrive** [comment]
> The output looks fine to me. I just checked the code and the `render_mode` (in `test_agent.py` line 27) is set to 'video', which means that it will directly store the output as a video. I forgot to make this a command line argument.
> There should be a folder `videos` containing the output video.
> 
> So, after all the issue was Python 3.6 vs 3.8?

**I tried to run the training test. However, it always said**   File "experiment.py", line 9, in <module>
    from baselines.common.vec_env.shmem_vec_env import ShmemVecEnv
ModuleNotFoundError: No module named 'baselines.common.vec_env.shmem_vec_env'. 

**I have actually add the baseline to the pythonpath as follows**
 export PYTHONPATH=/home/dongyang/anaconda3/envs/score_following/lib/python3.6/site-packages


**And the python can import baselines with the activated environment. Do you have some idea about this problem? **

e-tismir-2019$ export PYTHONPATH=/home/dongyang/anaconda3/envs/score_following/lib/python3.6/site-packages
(score_following) dongyang@dongyang-G5-5590:~/ScoreFollowing/score_following_game-tismir-2019$ python
Python 3.6.12 |Anaconda, Inc.| (default, Sep  8 2020, 23:10:56) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path
['', '/home/dongyang/anaconda3/envs/score_following/lib/python3.6/site-packages', '/home/dongyang/anaconda3/envs/score_following/lib/python36.zip', '/home/dongyang/anaconda3/envs/score_following/lib/python3.6', '/home/dongyang/anaconda3/envs/score_following/lib/python3.6/lib-dynload', '/home/dongyang/.local/lib/python3.6/site-packages', '/home/dongyang/ScoreFollowing/score_following_game-tismir-2019']
>>> 
(score_following) dongyang@dongyang-G5-5590:~/ScoreFollowing/score_following_game-tismir-2019$ python experiment.py --net ScoreFollowingNetNottinghamLS --train_set /home/dongyang/ScoreFollowing/score_following_game-tismir-2019/score_following_game/data/nottingham/nottingham_train --eval_set /home/dongyang/ScoreFollowing/score_following_game-tismir-2019/score_following_game/data/nottingham/nottingham_valid --game_config game_configs/nottingham_ls1.yaml --log_root /home/dongyang/ScoreFollowing/score_following_game-tismir-2019/log --param_root /home/dongyang/ScoreFollowing/score_following_game-tismir-2019/param --agent ppo
Traceback (most recent call last):
  File "experiment.py", line 9, in <module>
    from baselines.common.vec_env.shmem_vec_env import ShmemVecEnv
ModuleNotFoundError: No module named 'baselines.common.vec_env.shmem_vec_env'
(score_following) dongyang@dongyang-G5-5590:~/ScoreFollowing/score_following_game-tismir-2019$ python
Python 3.6.12 |Anaconda, Inc.| (default, Sep  8 2020, 23:10:56) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import baselines
>>>

**Comment by AutoNeuroDrive** [comment]
> The output looks fine to me. I just checked the code and the `render_mode` (in `test_agent.py` line 27) is set to 'video', which means that it will directly store the output as a video. I forgot to make this a command line argument.
> There should be a folder `videos` containing the output video.
> 
> So, after all the issue was Python 3.6 vs 3.8?

I checked my baselines package, there is actually no ShmemVecEnv.py. Could you please send me the file? If so, lidongyang0412@163.com and ldytongji0412@gmail.com are both Ok.

Thank you very much!!!

**Comment by AutoNeuroDrive** [comment]
Hi, the baselines has been solved and the training can be run now! Thanks for you attention!!!


Best Regards!
Dongyang Li
---------------------------------
Dongyang Li
Department of Control Science and Engineering
College of Electronics and Information Engineering
Tongji University
Shanghai, China
Address: 4800 Cao’an Rd.Shanghai, China 201804
Tel: + 86 13167236548
Email: lidongyang0412@163.com


On 2/20/2021 17:33，Dongyang Li<lidongyang0412@163.com> wrote：
The python version I used now is 3.6.  Furthermore, did you set some additional settings for jack?


Best Regards!
Dongyang Li
---------------------------------
Dongyang Li
Department of Control Science and Engineering
College of Electronics and Information Engineering
Tongji University
Shanghai, China
Address: 4800 Cao’an Rd.Shanghai, China 201804
Tel: + 86 13167236548
Email: lidongyang0412@163.com


On 2/20/2021 16:50，Dongyang Li<lidongyang0412@163.com> wrote：
I still can not run the human-test code. The outputs are obtained by run the optimal-test. I will try to train the network.


I guess it should be the system version, but I am not sure.....


Thanks very much for your attentions!!!


Best Regards!
Dongyang Li
---------------------------------
Dongyang Li
Department of Control Science and Engineering
College of Electronics and Information Engineering
Tongji University
Shanghai, China
Address: 4800 Cao’an Rd.Shanghai, China 201804
Tel: + 86 13167236548
Email: lidongyang0412@163.com


On 2/20/2021 15:26，Florian Henkel<notifications@github.com> wrote：

The output looks fine to me. I just checked the code and the render_mode (in test_agent.py line 27) is set to 'video', which means that it will directly store the output as a video. I forgot to make this a command line argument.
There should be a folder videos containing the output video.

So, after all the issue was Python 3.6 vs 3.8?

**Comment by fhenkel** [comment]
Glad to hear that it works now. 
I will close the issue now, in case you need more help or have further questions you can also drop me a mail!

**Comment by AutoNeuroDrive** [comment]
Hi, the code has run for about two days on the data set of Nottingham, is it normal? The current stutus of the model is listed as follows.


|update                125700 |
| duration(s)            130.4 |
| policy_loss         -0.02629 |
| value_loss           0.00724 |
| entropy              0.53174 |
| explained_var      116.43096 |
| avg_reward         915.89270 |
| median_reward     1004.71069 |
| ppo_epsilon          0.20000 |
| steps               15084128 |
| learn_rate           0.00010 |











--

Best Regards!
Dongyang Li
---------------------------------
Dongyang Li
Department of Control Science and Engineering
College of Electronics and Information Engineering
Tongji University
Shanghai, China
Address: 4800 Cao’an Rd.Shanghai, China 201804
Tel: + 86 13167236548
Email: lidongyang0412@163.com






At 2021-02-21 17:28:14, "Florian Henkel" <notifications@github.com> wrote:

Glad to hear that it works now.
I will close the issue now, in case you need more help or have further questions you can also drop me a mail!

**Comment by fhenkel** [comment]
As far as I remember that looks good, but to be sure you should also run `evaluate_agent.py``with your trained agent (see README).
